### ISSUE TITLE
Availability on conga-forge

### ISSUE THREAD

**Issue by ilyanoskov** [javiber/elephant#7]
Dear @javiber,

Thanks a lot for this repo!

Is there any chance you can make it available on conda-forge?

**Comment by javiber** [comment]
Hi @ilyanoskov,

I'm sorry for not getting back to you sooner, I hadn't turned on the notifications for this repo yet.

I don't have much experience publishing to conda and poetry [refuses](https://github.com/python-poetry/poetry/issues/3376) to support it so this probably will not be implemented any time soon unfortunately.

I'm open to any contribution that can make this possible though.

Cheers
